name: mot-env
channels:
  - conda-forge
dependencies:
  - python=3.9.23
  - pip=25.2
  - setuptools=80.9.0
  - wheel=0.45.1
  - ca-certificates
  - openssl
  - tk
  - bzip2
  - xz
  - zlib
  - ncurses
  - readline
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.0
      - annotated-types==0.7.0
      - anywidget==0.9.18
      - asttokens==3.0.0
      - bbox-visualizer==0.2.2
      - beautifulsoup4==4.13.4
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - comm==0.2.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==3.1.2
      - decorator==5.2.1
      - defusedxml==0.7.1
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fairscale==0.4.13
      - filelock==3.18.0
      - filetype==1.2.0
      - fonttools==4.59.0
      - fsspec==2025.7.0
      - ftfy==6.3.1
      - gdown==5.2.0
      - grpcio==1.74.0
      - hf-xet==1.1.7
      - huggingface-hub==0.34.4
      - idna==3.7
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipython==8.18.1
      - ipywidgets==8.1.7
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - jupyter-bbox-widget==0.6.0
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - lap==0.5.12
      - loguru==0.7.3
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - numpy==1.24.4
      - open-clip-torch==3.1.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.10.0.84
      - packaging==25.0
      - pandas==2.3.1
      - parso==0.8.4
      - peft==0.17.0
      - pexpect==4.9.0
      - pi-heif==1.1.0
      - pillow==11.3.0
      - pillow-avif-plugin==1.5.2
      - polygraphy==0.49.26
      - prompt-toolkit==3.0.51
      - protobuf==6.31.1
      - psutil==7.0.0
      - psygnal==0.14.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.10
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pylabel==0.1.55
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.4
      - requests-toolbelt==1.0.0
      - rf100vl==1.0.0
      - rfdetr==1.2.1
      - roboflow==1.2.3
      - safetensors==0.6.2
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - six==1.17.0
      - soupsieve==2.7
      - stack-data==0.6.3
      - supervision==0.26.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - timm==1.0.19
      - tokenizers==0.21.4
      - torch==2.8.0
      - torchreid==0.2.5
      - torchvision==0.23.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.55.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - yacs==0.1.8
      - zipp==3.23.0
